### ISSUE TITLE
Icons look horrible in font size 14, but too big in font size 16

### ISSUE THREAD

**Issue by VoltaVX** [Kudostoy0u/pwsh10k#1]
I think this is more of a windows terminal problem, but I noticed that the Windows icon for instance looks extremely pixelated when the font isn't too big. But if I change it to the point where it looks good again, the font size ends up being WAYYYY too big. Do you by any chance now any workarounds for this?

**Comment by Kudostoy0u** [comment]
It is probably a Windows Terminal problem (when I resize my terminal or zoom in things look weird)
Can you send a screenshot of size 14 and size 16? 
It would help me see what the problem looks like.

**Comment by fernandolamp** [comment]
The icon \ue62a look better on this size
