### ISSUE TITLE
"how to configure a theme" from readme returns a 404

### ISSUE THREAD

**Issue by RavingSmurfGB** [Kudostoy0u/pwsh10k#11]
Heya, First of all awesome theme!!! 

Im trying to figure out how to recreate my ZSH theme however the ([how to configure a theme?](https://ohmyposh.dev/docs/config-overview)) from the readme returns a 404.

Any chance that you can re-upload the documentation somewhere on github?
- Maybe the Ohmyposh.dev URL get changed

**Comment by Kudostoy0u** [comment]
Hi, 

Glad to see there's still interest in this repo! After a quick look on the site, I've located the new configuration page [here](https://ohmyposh.dev/docs/configuration/general). Feel free to close the issue if this helps, or let me know if it doesn't!

**Comment by RavingSmurfGB** [comment]
Thank you so much :)
