### ISSUE TITLE
Icons issue

### ISSUE THREAD

**Issue by fernandolamp** [Kudostoy0u/pwsh10k#3]
Hi! 

Thank you for your theme, it's  awesome.

But i have icons issues, first :

Charged Battery icon is a tree: 

![image](https://user-images.githubusercontent.com/18193204/128779015-de9a0854-97a5-4244-a538-0f571065d0a8.png)

`"charged_icon": "\uE22F "`

Looking for this icon on nerd fonts https://www.nerdfonts.com/cheat-sheet i found :

![image](https://user-images.githubusercontent.com/18193204/128779216-9f1c0440-c81d-4642-9fa1-21f977107d1e.png)

Charging icon is wrong too ❌ :

"charging_icon": "\uE234 ",

![image](https://user-images.githubusercontent.com/18193204/128779620-0e6b2da8-d6c6-4d25-9441-aae5ddb509a5.png)

![image](https://user-images.githubusercontent.com/18193204/128779423-76b07e6d-f2a0-4144-b25c-48ccc36fcdf0.png)

Dischargind icon is correct ✅ :

![image](https://user-images.githubusercontent.com/18193204/128779518-8db7b30a-9910-4f76-9439-600ef4e11de1.png)

Related #2 

My posh version is  3.171.2

**Comment by Kudostoy0u** [comment]
Thank you for the improvement of pwsh10k!
