### ISSUE TITLE
Make your own prompt w/ setup wizard

### ISSUE THREAD

**Issue by Zeratoxx** [Kudostoy0u/pwsh10k#6]
Not quite an issue but is there a way to somehow export the theme from p10k from a Linux-shell? Or did you create the json by hand?

**Comment by Kudostoy0u** [comment]
AFAIK there is no way to convert a `.p10k.zsh` config file into a `.omp.json` one for `oh-my-posh3` unfortunately. I custom made this theme with JSON.

If you would like me to recreate your powerlevel10k theme for powershell though, let me know 😉

**Comment by Zeratoxx** [comment]
Well, that's a pity.

But yes, I would love if you could recreate my theme :3
As long as it doesn't take too much of your time of course! It has to be the lowest prio :)

**Comment by Kudostoy0u** [comment]
Yep, just send me a screen shot of the prompt and I'll see towards recreating it!

**Comment by LLBlumire** [comment]
Hello, I'm not the original poster of this issue but I'd also be super interested in this, my p10k.zsh is here

https://gist.github.com/LLBlumire/5baed113d20cc3cb1a0882199b038cac

and it looks like 

![image](https://user-images.githubusercontent.com/6872380/145440338-383fe9d4-87d7-4cef-ade6-72479a96502f.png)

**Comment by Kudostoy0u** [comment]
Sure!

Though I might end up making pwsh10k into a script to make your own prompt (like powerlevel10k), then anyone can use the script to replicate their ideal prompt for powershell.

**Comment by LLBlumire** [comment]
That would be amazing!

**Comment by Zeratoxx** [comment]
I use two different configs:

1. https://gist.github.com/Zeratoxx/ddb4bbd5ef4e645c28a27d0b32d0c5ee
Screenshot:
![grafik](https://user-images.githubusercontent.com/35294329/145458591-b56861e1-fec3-4c88-9b49-c4746f16cafb.png)

2. https://gist.github.com/Zeratoxx/79bdba59bd926d04e6502d7a2f9f1ed9
Screenshot:
![grafik](https://user-images.githubusercontent.com/35294329/145459744-cae9776d-fbf2-42da-b2c8-d4b88bf93178.png)

**Comment by Kudostoy0u** [comment]
Sorry for the late follow up, I've been quite occupied :sweat_smile:. I'm not going to do the setup wizard like in powerlevel10k, it shows to be a much bigger undertaking than my first impression.

Here are your prompts:
@Zeratoxx 
Config 1: https://pastebin.com/QnnnszRL
Config 2: https://pastebin.com/rYTwBtda
@LLBlumire 
Config 1: https://pastebin.com/BAAEhWpB

(Unfortunately [a connector between the two sides of the prompt is not supported](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1472))

**Comment by Zeratoxx** [comment]
Thank you ❤️❤️

**Comment by Kudostoy0u** [comment]
No problem ;)

Feel free to reopen for any questions or issues!
