### ISSUE TITLE
Is there any way to put the cursor into next line? 

### ISSUE THREAD

**Issue by farhancdr** [Kudostoy0u/pwsh10k#7]
## I want to put my cursor pointer on next line! What I need to put on json file can you please suggest ? 
[![pwsh10k-issue.png](https://i.postimg.cc/ZqRzX7qr/pwsh10k-issue.png)](https://postimg.cc/K1dWM5Bz)

**Comment by Kudostoy0u** [comment]
Well, to do that without a tail on the prompt, it's simply appending `\n` to the `trailing_diamond` attribute on the last segment, which results in as shown below:
![image](https://user-images.githubusercontent.com/69732000/148695960-6c8c20dc-9ce7-42ee-be13-3431b7c6bbaa.png)

Here's the json for this!
https://pastebin.com/9pyYDnYc

**Comment by Kudostoy0u** [comment]
Yes, that can be done by creating a new "prompt" block on a new line!
Here's a preview of what it looks like:
![image](https://user-images.githubusercontent.com/69732000/148697430-a790916f-9fd9-442b-a608-f18079c03cc4.png)

Here's the json code you're looking for:
https://pastebin.com/THQywwgw

**Comment by farhancdr** [comment]
> Yes, that can be done by creating a new "prompt" block on a new line! Here's a preview of what it looks like: ![image](https://user-images.githubusercontent.com/69732000/148697430-a790916f-9fd9-442b-a608-f18079c03cc4.png)
> 
> Here's the json code you're looking for: https://pastebin.com/THQywwgw

Thank you so much! It is working!
