### ISSUE TITLE
Mention possible issues that a user may face

### ISSUE THREAD

**Issue by lazycipher** [Kudostoy0u/pwsh10k#8]
It'll be better to list or mention possible issues a user may face.
For example: Windows `curl` isn't actual `cURL` so it won't accept `--output`.
ref: https://stackoverflow.com/questions/25044010/running-curl-on-64-bit-windows

**Comment by lazycipher** [comment]
The issue `PowerShell_profile.ps1 cannot be loaded because running scripts is disabled on this 
system`

**Comment by Kudostoy0u** [comment]
Thanks, updated the README!

Feel free to reopen if you find any issues.
